version: '3'

services:
  react-app:
      build:  
        context: ../checklist-frontend
        dockerfile: Dockerfile
      container_name: checklist-v2
      networks:
        - checklist-v2-networks
      restart: always
      depends_on:
        - react-php
      ports:
        - 3002:80
      volumes:
       - ./nginx/checklist.conf:/etc/nginx/conf.d/default.conf
       - ../checklist-backend:/var/www/html/checklistv2/api

  react-mysql:
      build:
        context: .
        dockerfile: Dockerfile.mysql
      container_name: checklist-v2-mysql 
      environment:
        - MYSQL_ROOT_PASSWORD=db
        - MYSQL_DATABASE=mydatabase
        - MYSQL_ROOT_HOST=%
      networks:
        - checklist-v2-networks
      restart: always
      ports:
       - 3306:3306
      volumes:
        - ./mysql_custom/my.cnf:/etc/my.cnf
        - ./mysql_data/:/var/lib/mysql
  react-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: checklist-v2-jenkins  
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - ./jenkins_checklistv2_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - checklist-v2-networks
    user: root
  react-php:
       build:
        context: ../checklist-backend
        dockerfile: Dockerfile
       container_name: checklist-v2-php
       networks:
        - checklist-v2-networks
       ports:
        - 3001:9000
       restart: always 
       volumes:
        - ../checklist-backend:/var/www/html/checklistv2/api
       depends_on:
        - react-mysql        
networks:
  checklist-v2-networks:
    driver: bridge
